# Generated by Django 5.2.8 on 2025-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='description',
            field=models.TextField(blank=True, help_text='detailed description of the leave', null=True, verbose_name='Description'),
        ),
    ]
