# Generated by Django 5.2.9 on 2026-02-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_companystaff_options'),
        ('leave', '0003_add_manager_to_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceleaves',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='user',
        ),
        migrations.AddField(
            model_name='balanceleaves',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_leaves', to='account.companystaff'),
        ),
        migrations.AddField(
            model_name='leave',
            name='admin_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_admin_approvals', to='account.companystaff', verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='leave',
            name='manager_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to='account.companystaff', verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='leave',
            name='needs_admin_approval',
            field=models.BooleanField(default=False, help_text='True when leave_days > 2'),
        ),
        migrations.AddField(
            model_name='leave',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='account.companystaff', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('manager_approved', 'Manager Approved'), ('admin_approved', 'Admin Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
