# Generated by Django 5.2.9 on 2026-09-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_remove_balanceleaves_staff_remove_leave_admin_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='pending_manager', max_length=30),
        ),
    ]
