# Generated by Django 5.2.9 on 2026-09-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_add_companystaff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaff',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companystaff',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('hr', 'HR'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20, verbose_name='role'),
        ),
    ]
