# Generated by Django 5.2.8 on 2025-11-24 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('administration', '0001_initial'),
        ('employee', '0001_initial'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asign',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_too', to='managers.manager'),
        ),
        migrations.AddField(
            model_name='asign',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='company',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AddField(
            model_name='managernotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.manager'),
        ),
        migrations.AddField(
            model_name='mtask',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='mtask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.manager'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_to', to='managers.manager'),
        ),
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
