# Generated by Django 5.2.8 on 2025-11-25 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('administration', '0002_initial'),
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAllDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_letter', models.FileField(blank=True, null=True, upload_to='documents/experience/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='documents/offer/')),
                ('education_certificate', models.FileField(blank=True, null=True, upload_to='documents/education/')),
                ('skill_certificate', models.FileField(blank=True, null=True, upload_to='documents/skill/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
