# Generated by Django 5.2.8 on 2025-11-28 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_employeealldocuments'),
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_letter', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('joining_letter', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('resignation_letter', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('other_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeAllDocuments',
        ),
    ]
