# Generated by Django 5.2.9 on 2025-12-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_employeedocument_delete_employeealldocuments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDocument',
        ),
    ]
