# Generated by Django 5.2.9 on 2025-12-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_delete_employeedocument'),
        ('employee', '0004_employeedocument_delete_employeefixeddocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_to', to='employee.employee'),
        ),
    ]
