# Generated by Django 5.2.9 on 2026-02-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_companystaff_options'),
        ('administration', '0007_emailnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asign',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='asign',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='managernotification',
            name='user',
        ),
        migrations.AddField(
            model_name='asign',
            name='manager_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_as_manager', to='account.companystaff', verbose_name='Assigned to (Manager)'),
        ),
        migrations.AddField(
            model_name='asign',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_as_employee', to='account.companystaff'),
        ),
        migrations.AddField(
            model_name='managernotification',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_notifications', to='account.companystaff'),
        ),
    ]
