# Generated by Django 5.2.9 on 2026-03-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_managerproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerproject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
