# Generated by Django 5.2.9 on 2026-03-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerpayroll', '0002_remove_salary_manager_salary_staff'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='staff',
        ),
        migrations.AddField(
            model_name='salary',
            name='manager',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.manager'),
        ),
    ]
