# Generated by Django 5.2.9 on 2026-09-30 10:39

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerpayroll', '0003_remove_salary_staff_salary_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Salary', 'verbose_name_plural': 'Salaries'},
        ),
        migrations.AlterField(
            model_name='salary',
            name='allowance',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='basic',
            field=core.encryption.EncryptedIntegerField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='salary',
            name='bonuses',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='conveyance',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='da_percent',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='esi',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='hra_percent',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True, verbose_name='House rent Allowance'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='labour_welfare',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='leave',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='loan_repayment',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='medical_allowance',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='others',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='providence_fund',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True, verbose_name='Provident Fund'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='tax',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='tds',
            field=core.encryption.EncryptedIntegerField(blank=True, default=0, max_length=255, null=True, verbose_name='Tax Deducted at Source (T.D.S.)'),
        ),
    ]
