# Generated by Django 5.2.9 on 2026-03-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_remove_asign_assigned_to_remove_asign_employee_and_more'),
        ('employee', '0006_remove_attendance_employee_and_more'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asign',
            name='manager_staff',
        ),
        migrations.RemoveField(
            model_name='asign',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='managernotification',
            name='staff',
        ),
        migrations.AddField(
            model_name='asign',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_too', to='managers.manager'),
        ),
        migrations.AddField(
            model_name='asign',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='managernotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.manager'),
        ),
    ]
