# Generated by Django 5.2.9 on 2026-03-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_attendance_staff_and_more'),
        ('managers', '0001_initial'),
        ('resign', '0002_remove_resign_assigned_too_remove_resign_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resign',
            name='admin_staff',
        ),
        migrations.RemoveField(
            model_name='resign',
            name='approved_by_staff',
        ),
        migrations.RemoveField(
            model_name='resign',
            name='staff',
        ),
        migrations.AddField(
            model_name='resign',
            name='assigned_too',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_assigned_too', to='managers.manager'),
        ),
        migrations.AddField(
            model_name='resign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='resign',
            name='status',
            field=models.CharField(default='pending', max_length=12),
        ),
    ]
