# Generated by Django 5.2.8 on 2025-11-24 10:32

import django.db.models.deletion
import django.utils.timezone
import managers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_first_name', models.CharField(max_length=100)),
                ('manager_last_name', models.CharField(max_length=100)),
                ('manager_email', models.EmailField(max_length=100)),
                ('manager_joining_date', models.DateField(max_length=50)),
                ('manager_designation', models.CharField(max_length=100)),
                ('manager_id', models.CharField(max_length=100)),
                ('manager_phone', models.CharField(max_length=100, null=True)),
                ('manager_salary', models.CharField(default=350000, max_length=100)),
                ('manager_birth_date', models.CharField(max_length=100, null=True)),
                ('manager_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('manager_father', models.CharField(max_length=100, null=True)),
                ('manager_mother', models.CharField(max_length=100, null=True)),
                ('manager_address', models.CharField(max_length=50, null=True)),
                ('manager_pin_code', models.CharField(max_length=50, null=True)),
                ('manager_state', models.CharField(max_length=50, null=True)),
                ('manager_country', models.CharField(max_length=50, null=True)),
                ('manager_image', models.FileField(blank=True, upload_to='media/')),
                ('manager_created_date', models.DateTimeField(auto_now=True)),
                ('manager_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=32)),
                ('manager_tel', models.CharField(max_length=50, null=True)),
                ('manager_nationality', models.CharField(max_length=50, null=True)),
                ('manager_religion', models.CharField(max_length=50, null=True)),
                ('manager_marital_status', models.CharField(max_length=50, null=True)),
                ('manager_emergency_primary_name', models.CharField(max_length=50, null=True)),
                ('manager_emergency_primary_relationship', models.CharField(max_length=50, null=True)),
                ('manager_emergency_primary_phone1', models.CharField(max_length=50, null=True)),
                ('manager_emergency_primary_phone2', models.CharField(max_length=50, null=True)),
                ('manager_education_institution', models.CharField(max_length=50, null=True)),
                ('manager_education_subject', models.CharField(max_length=50, null=True)),
                ('manager_education_starting_date', models.CharField(max_length=50, null=True)),
                ('manager_education_complete_date', models.CharField(max_length=50, null=True)),
                ('manager_education_degree', models.CharField(max_length=50, null=True)),
                ('manager_education_grade', models.CharField(max_length=50, null=True)),
                ('manager_experience_company_name', models.CharField(max_length=50, null=True)),
                ('manager_experience_company_location', models.CharField(max_length=50, null=True)),
                ('manager_experience_company_job_position', models.CharField(max_length=50, null=True)),
                ('manager_experience_company_period_from', models.CharField(max_length=50, null=True)),
                ('manager_experience_company_period_to', models.CharField(max_length=50, null=True)),
                ('manager_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='account.companystaff')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.manager')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_time', models.DateTimeField(validators=[managers.models.validate_start_time])),
                ('end_time', models.DateTimeField(validators=[managers.models.validate_end_time])),
                ('project', models.CharField(max_length=500, null=True)),
                ('activity', models.CharField(max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entry',
            },
        ),
        migrations.CreateModel(
            name='ManagerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_letter', models.FileField(null=True, upload_to='Files')),
                ('offer_letter', models.FileField(null=True, upload_to='Files')),
                ('education_certificate', models.FileField(null=True, upload_to='Files')),
                ('skill_certificate', models.FileField(null=True, upload_to='Files')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.manager')),
            ],
        ),
    ]
