# Generated by Django 5.2.9 on 2026-07-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='biometric_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
