# Generated by Django 5.2.9 on 2026-09-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_manager_biometric_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerattendance',
            options={'ordering': ['-check_in']},
        ),
        migrations.AddField(
            model_name='manager',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
