# Generated by Django 5.2.9 on 2026-09-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_alter_managerattendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerpost',
            name='education_certificate',
            field=models.FileField(blank=True, null=True, upload_to='Files'),
        ),
        migrations.AlterField(
            model_name='managerpost',
            name='experience_letter',
            field=models.FileField(blank=True, null=True, upload_to='Files'),
        ),
        migrations.AlterField(
            model_name='managerpost',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='Files'),
        ),
        migrations.AlterField(
            model_name='managerpost',
            name='skill_certificate',
            field=models.FileField(blank=True, null=True, upload_to='Files'),
        ),
    ]
