# Generated by Django 5.2.9 on 2025-12-09 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeefixeddocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_letter', models.FileField(blank=True, null=True, upload_to='employee_docs/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='employee_docs/')),
                ('education_certificate', models.FileField(blank=True, null=True, upload_to='employee_docs/')),
                ('skill_certificate', models.FileField(blank=True, null=True, upload_to='employee_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeFixedDocuments',
        ),
    ]
