# Generated by Django 5.2.9 on 2026-08-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_biometric_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='activity',
            new_name='task',
        ),
    ]
