# Generated by Django 5.2.9 on 2026-08-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_rename_activity_entries_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='blocker_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
