# Generated by Django 5.2.9 on 2026-09-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_employee_employee_reports_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-check_in']},
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
