"""
Django settings for dstt project.





Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
# """

import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

import socket
import sweetify

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'dev-only-insecure-key-change-before-production',
)
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() in {'1', 'true', 'yes'}
ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        'localhost,127.0.0.1,eagleinclouds.com,www.eagleinclouds.com,hrms.eagleinclouds.com,50.19.21.0,*.amazonaws.com,*',
    ).split(',') if host.strip()
]

# Master 256-bit encryption key for PII & Financial data
FERNET_ENCRYPTION_KEY = os.environ.get(
    'FERNET_ENCRYPTION_KEY',
    'bNn5A3CtVw2wVtJVXxkPyk55FW5x_Z9wTnz1Eyodjmk=',
)

# CSRF Trusted Origins for domain, ngrok and other external origins
CSRF_TRUSTED_ORIGINS = [
    'https://eagleinclouds.com',
    'http://eagleinclouds.com',
    'https://www.eagleinclouds.com',
    'http://www.eagleinclouds.com',
    'https://hrms.eagleinclouds.com',
    'http://hrms.eagleinclouds.com',
    'https://*.eagleinclouds.com',
    'http://*.eagleinclouds.com',
    'http://50.19.21.0',
    'https://50.19.21.0',
    'http://50.19.21.0:8001',
    'http://*.amazonaws.com',
    'http://*.amazonaws.com:8001',
    'https://*.amazonaws.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:8001',
    'http://127.0.0.1:8001',
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
    'https://*.ngrok.io',
]

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False

DATE_INPUT_FORMATS = ('%d/%m/%Y','%d-%m-%Y','%Y-%m-%d')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'administration.apps.AdministrationConfig',
    'account.apps.AccountConfig',
    'management.apps.ManagementConfig',
    'employee.apps.EmployeeConfig',
    'core',
   
    'crispy_forms',
    'crispy_bootstrap4',

    'sweetify',
    'bulma',
    'password_reset',

    'leave.apps.LeaveConfig',
    'payroll.apps.PayrollConfig',
    'managers.apps.ManagersConfig',
    'manageregularization.apps.ManagerRegularizationConfig',
    'regularization.apps.RegularizationConfig',
    'managerpayroll.apps.ManagerPayrollConfig',
    'resign.apps.ResignConfig',
    'manager_resign.apps.ManagerResignConfig',
    'manager_leave.apps.ManagerLeaveConfig',
    'biometric.apps.BiometricConfig',

    'bootstrap4',
]


MIDDLEWARE = [
    'biometric.middleware.NormalizeDoubleSlashMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'account.middleware.HttpsDomainRedirectMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'account.middleware.SessionSecurityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'employee.context_processors.employee_notifications',
                'account.context_processors.admin_company_staff',
            ],
        },
    },
]

WSGI_APPLICATION = 'dstt.wsgi.application'


try:
    import dj_database_url
except ImportError:
    dj_database_url = None

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

if dj_database_url and os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=0,
        conn_health_checks=True,
    )
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'require',
        'keepalives': 1,
        'keepalives_idle': 30,
        'keepalives_interval': 10,
        'keepalives_count': 5,
    }


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_L10N = True
USE_TZ = True

LOGIN_URL = '/hrms/'
LOGOUT_REDIRECT_URL = '/hrms/'

# STATIC_URL = '/static/'
# # STATIC_ROOT = os.path.join('static')
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'



MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

AUTH_USER_MODEL = 'account.User'

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
}

#  CRISPY FIX (VERY IMPORTANT)
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

SWEETIFY_SWEETALERT_LIBRARY = 'sweetalert2'
sweetify.DEFAULT_OPTS = {
    'showConfirmButton': True,
    'timer': 3000,
    'allowOutsideClick': True,
    'confirmButtonText': 'OK',
}

PUBLIC_API_BASE_URL = os.environ.get('PUBLIC_API_BASE_URL', 'http://127.0.0.1:8000')
BIOMETRIC_TCP_HOST = os.environ.get('BIOMETRIC_TCP_HOST', '0.0.0.0')
BIOMETRIC_TCP_PORT = int(os.environ.get('BIOMETRIC_TCP_PORT', '5005'))
BIOMETRIC_TCP_SOCKET_TIMEOUT = int(os.environ.get('BIOMETRIC_TCP_SOCKET_TIMEOUT', '10'))
BIOMETRIC_TCP_MAX_PAYLOAD_BYTES = int(os.environ.get('BIOMETRIC_TCP_MAX_PAYLOAD_BYTES', str(1024 * 1024)))
BIOMETRIC_TCP_ACK_MESSAGE = os.environ.get('BIOMETRIC_TCP_ACK_MESSAGE', 'OK')

ROOT_URLCONF = 'dstt.urls'
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Gmail IMAP Configuration (for reading inquiry emails from Gmail inbox)
GMAIL_IMAP_HOST = 'imap.gmail.com'
GMAIL_IMAP_PORT = 993
GMAIL_EMAIL = os.environ.get('GMAIL_EMAIL', '')
GMAIL_APP_PASSWORD = os.environ.get('GMAIL_APP_PASSWORD', '')

# Gmail SMTP Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' if (GMAIL_EMAIL and GMAIL_APP_PASSWORD) else 'django.core.mail.backends.dummy.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = GMAIL_EMAIL
EMAIL_HOST_PASSWORD = GMAIL_APP_PASSWORD
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL') or f'Eagle In Cloud Contact <{GMAIL_EMAIL}>' if GMAIL_EMAIL else 'noreply@eagleincloud.io'
EMAIL_TIMEOUT = 10

# Logging - so leave/email notification logs show in console
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'administration.email_notifications': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
