# Generated by Django 5.2.9 on 2026-03-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_attendance_staff_and_more'),
        ('leave', '0004_remove_balanceleaves_user_remove_leave_manager_and_more'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceleaves',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='admin_staff',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='manager_staff',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='needs_admin_approval',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='staff',
        ),
        migrations.AddField(
            model_name='balanceleaves',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='leave',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managers.manager', verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='pending', max_length=12),
        ),
    ]
