# Generated by Django 5.2.9 on 2026-09-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leave_manager_approved_leave_manager_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('paid', 'Paid Leave')], default='paid', max_length=25, null=True, verbose_name='Leave Type'),
        ),
    ]
