# Generated by Django 5.2.9 on 2026-02-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_companystaff_options'),
        ('manager_resign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerresign',
            name='user',
        ),
        migrations.AddField(
            model_name='managerresign',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_resign_requests', to='account.companystaff'),
        ),
    ]
