# Generated by Django 5.2.8 on 2025-12-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerleave',
            name='description',
            field=models.TextField(blank=True, help_text='detailed description of the leave', null=True, verbose_name='Description'),
        ),
    ]
