# Generated by Django 5.2.9 on 2026-02-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_companystaff_options'),
        ('manager_leave', '0004_remove_balanceleave_enddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceleave',
            name='user',
        ),
        migrations.RemoveField(
            model_name='managerleave',
            name='user',
        ),
        migrations.AddField(
            model_name='balanceleave',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_balance_leaves', to='account.companystaff'),
        ),
        migrations.AddField(
            model_name='managerleave',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_leave_requests', to='account.companystaff'),
        ),
    ]
