# Generated by Django 5.2.9 on 2026-07-13 07:17

import biometric.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_add_companystaff_role'),
        ('employee', '0008_employee_biometric_id'),
        ('managers', '0002_manager_biometric_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('site_label', models.CharField(blank=True, default='', max_length=120)),
                ('device_type', models.CharField(choices=[('fingerprint', 'Fingerprint'), ('rfid', 'RFID'), ('hybrid', 'Hybrid')], default='hybrid', max_length=20)),
                ('integration_mode', models.CharField(choices=[('bridge_pull', 'Bridge Pull'), ('tcp_xml_push', 'TCP XML Push'), ('http_push', 'HTTP/HTTPS Push'), ('manual', 'Manual/API Import')], default='bridge_pull', max_length=20)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('serial_number', models.CharField(blank=True, default='', max_length=120)),
                ('terminal_id', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('allowed_source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=5005)),
                ('device_password', models.PositiveIntegerField(default=0)),
                ('machine_number', models.PositiveIntegerField(default=1)),
                ('bridge_server_url', models.URLField(blank=True, default='')),
                ('secret_key', models.CharField(default=biometric.models.generate_device_secret_key, max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_punch_at', models.DateTimeField(blank=True, null=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_test_message', models.CharField(blank=True, default='', max_length=255)),
                ('last_event_type', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('manual', 'Manual/API'), ('bridge', 'Bridge Pull'), ('http', 'HTTP/HTTPS Push'), ('tcp_xml', 'TCP XML Push')], default='manual', max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=80)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=120)),
                ('biometric_user_id', models.CharField(max_length=100)),
                ('verify_mode', models.CharField(blank=True, default='', max_length=100)),
                ('punch_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('applied', 'Applied'), ('duplicate', 'Duplicate'), ('unmatched', 'Unmatched'), ('invalid', 'Invalid'), ('error', 'Error')], default='received', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.attendance')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='biometric.biometricdevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managers.manager')),
                ('manager_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managers.managerattendance')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['biometric_user_id', 'punch_time'], name='biometric_b_biometr_438691_idx'), models.Index(fields=['status', 'received_at'], name='biometric_b_status_1285f9_idx'), models.Index(fields=['device', 'received_at'], name='biometric_b_device__79f3b5_idx')],
            },
        ),
    ]
