# Generated by Django 5.2.9 on 2026-08-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometriceventlog',
            name='protocol',
            field=models.CharField(choices=[('manual', 'Manual/API'), ('bridge', 'Bridge Pull'), ('http', 'HTTP/HTTPS Push'), ('tcp_xml', 'TCP XML Push'), ('adms_push', 'ADMS Push')], default='manual', max_length=20),
        ),
    ]
