# Generated by Django 5.2.9 on 2026-02-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_companystaff_options'),
        ('regularization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularization',
            name='r_assigned_to',
        ),
        migrations.RemoveField(
            model_name='regularization',
            name='user',
        ),
        migrations.AddField(
            model_name='regularization',
            name='manager_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regularization_approvals', to='account.companystaff'),
        ),
        migrations.AddField(
            model_name='regularization',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regularization_requests', to='account.companystaff'),
        ),
    ]
