# Generated by Django 5.2.9 on 2026-03-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_attendance_staff_and_more'),
        ('managers', '0001_initial'),
        ('regularization', '0002_remove_regularization_r_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularization',
            name='manager_staff',
        ),
        migrations.RemoveField(
            model_name='regularization',
            name='staff',
        ),
        migrations.AddField(
            model_name='regularization',
            name='r_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_assigned_to', to='managers.manager'),
        ),
        migrations.AddField(
            model_name='regularization',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
