# Generated by Django 5.2.9 on 2026-02-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_companystaff_options'),
        ('resign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resign',
            name='assigned_too',
        ),
        migrations.RemoveField(
            model_name='resign',
            name='user',
        ),
        migrations.AddField(
            model_name='resign',
            name='admin_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resign_admin_approvals', to='account.companystaff', verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='resign',
            name='approved_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resign_approvals', to='account.companystaff', verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='resign',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resign_requests', to='account.companystaff'),
        ),
        migrations.AlterField(
            model_name='resign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('manager_approved', 'Manager Approved'), ('admin_approved', 'Admin Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
