# Generated by Django 5.2.9 on 2026-03-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_attendance_staff_and_more'),
        ('payroll', '0002_remove_salary_employee_salary_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='staff',
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
