# Generated by Django 5.2.9 on 2026-09-16 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_alter_managerpost_education_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='manager_reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_managers', to='managers.manager'),
        ),
    ]
