# Generated by Django 5.2.9 on 2026-09-30 10:39

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0005_manager_manager_reports_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_address',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_birth_date',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_emergency_primary_phone1',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_emergency_primary_phone2',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_phone',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_pin_code',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_salary',
            field=core.encryption.EncryptedCharField(blank=True, default='350000', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_tel',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
