# Generated by Django 5.2.8 on 2025-12-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_leave', '0002_managerleave_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceleave',
            name='enddate',
            field=models.DateField(blank=True, help_text='leave end date', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='balanceleave',
            name='reason',
            field=models.TextField(blank=True, help_text='reason for leave', null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='balanceleave',
            name='startdate',
            field=models.DateField(blank=True, help_text='leave start date', null=True, verbose_name='Start Date'),
        ),
    ]
