# Generated by Django 5.2.8 on 2025-12-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_leave', '0003_balanceleave_enddate_balanceleave_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceleave',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='balanceleave',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='balanceleave',
            name='startdate',
        ),
    ]
