# Generated by Django 5.2.9

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
        ('manager_leave', '0006_remove_balanceleave_staff_remove_managerleave_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerleave',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_leave_requests_for_approval', to='managers.manager', verbose_name='Reporting to / Approving Manager'),
        ),
    ]
