# Generated by Django 5.2.9 on 2026-09-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_leave', '0007_managerleave_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerleave',
            name='leavetype',
            field=models.CharField(choices=[('paid', 'Paid Leave')], default='paid', max_length=25, null=True, verbose_name='Leave Type'),
        ),
    ]
