# Generated by Django 5.2.9 on 2026-02-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companystaff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
