# Generated by Django 5.2.9 on 2026-03-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_companystaff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companystaff',
            options={},
        ),
    ]
