# Generated by Django 5.2.9 on 2026-09-29 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_link_hr_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystaff',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='companystaff',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
