# Generated by Django 5.2.17 on 2026-09-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0002_alter_biometriceventlog_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometriceventlog',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('applied', 'Applied'), ('duplicate', 'Duplicate'), ('unmatched', 'Unmatched'), ('invalid', 'Invalid'), ('error', 'Error'), ('ignored', 'Ignored')], default='received', max_length=20),
        ),
    ]
