# Generated by Django 5.2.8 on 2025-11-24 10:32

import django.db.models.deletion
import manageregularization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRegularization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(null=True, validators=[manageregularization.models.validate_start_time])),
                ('check_out', models.DateTimeField(null=True, validators=[manageregularization.models.validate_end_time])),
                ('reason', models.CharField(blank=True, help_text='add additional information for Regularization', max_length=255, null=True, verbose_name='Reason for Regularization')),
                ('status', models.CharField(default='pending', max_length=12)),
                ('is_approved', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='managers.manager')),
            ],
            options={
                'verbose_name': 'Regularization',
                'verbose_name_plural': 'Regularization',
                'ordering': ['-created'],
            },
        ),
    ]
