# Generated by Django 5.2.9 on 2026-03-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageregularization', '0002_remove_mregularization_user_mregularization_staff'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mregularization',
            name='staff',
        ),
        migrations.AddField(
            model_name='mregularization',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='managers.manager'),
        ),
    ]
