# Generated by Django 5.2.8 on 2025-11-24 10:32

import django.db.models.deletion
import django.utils.timezone
import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('start_time', models.DateTimeField(validators=[employee.models.validate_start_time])),
                ('end_time', models.DateTimeField(validators=[employee.models.validate_end_time])),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('project', models.CharField(max_length=500, null=True)),
                ('activity', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_letter', models.FileField(null=True, upload_to='Files', verbose_name='Experience Letter')),
                ('offer_letter', models.FileField(null=True, upload_to='Files', verbose_name='Offer Letter')),
                ('education_certificate', models.FileField(null=True, upload_to='Files', verbose_name='Education Certificate')),
                ('skill_certificate', models.FileField(null=True, upload_to='Files', verbose_name='Skill Certificate')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_Name', models.CharField(max_length=100)),
                ('Department_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_first_name', models.CharField(max_length=100)),
                ('employee_last_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=100)),
                ('employee_joining_date', models.DateField(max_length=50)),
                ('employee_designation', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('employee_phone', models.CharField(max_length=100, null=True)),
                ('employee_salary', models.CharField(default=350000, max_length=100)),
                ('employee_birth_date', models.CharField(max_length=100, null=True)),
                ('employee_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('employee_address', models.CharField(max_length=50, null=True)),
                ('employee_pin_code', models.CharField(max_length=50, null=True)),
                ('employee_state', models.CharField(max_length=50, null=True)),
                ('employee_country', models.CharField(max_length=50, null=True)),
                ('employee_image', models.FileField(blank=True, upload_to='media/')),
                ('employee_created_date', models.DateTimeField(auto_now=True)),
                ('employee_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=32)),
                ('employee_tel', models.CharField(max_length=50, null=True)),
                ('employee_nationality', models.CharField(max_length=50, null=True)),
                ('employee_marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50, null=True)),
                ('employee_father', models.CharField(max_length=50, null=True)),
                ('employee_mother', models.CharField(max_length=50, null=True)),
                ('employee_emergency_primary_name', models.CharField(max_length=50, null=True)),
                ('employee_emergency_primary_relationship', models.CharField(max_length=50, null=True)),
                ('employee_emergency_primary_phone1', models.CharField(max_length=50, null=True)),
                ('employee_emergency_primary_phone2', models.CharField(max_length=50, null=True)),
                ('employee_education_institution', models.CharField(max_length=50, null=True)),
                ('employee_education_subject', models.CharField(max_length=50, null=True)),
                ('employee_education_starting_date', models.CharField(max_length=50, null=True)),
                ('employee_education_complete_date', models.CharField(max_length=50, null=True)),
                ('employee_education_degree', models.CharField(max_length=50, null=True)),
                ('employee_education_grade', models.CharField(max_length=50, null=True)),
                ('employee_experience_company_name', models.CharField(max_length=50, null=True)),
                ('employee_experience_company_location', models.CharField(max_length=50, null=True)),
                ('employee_experience_company_job_position', models.CharField(max_length=50, null=True)),
                ('employee_experience_company_period_from', models.CharField(max_length=50, null=True)),
                ('employee_experience_company_period_to', models.CharField(max_length=50, null=True)),
                ('employee_department', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
            ],
        ),
    ]
