# Generated by Django 5.2.8 on 2025-12-01 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFixedDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_letter', models.FileField(blank=True, null=True, upload_to='employee_documents/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='employee_documents/')),
                ('education_certificate', models.FileField(blank=True, null=True, upload_to='employee_documents/')),
                ('skill_certificate', models.FileField(blank=True, null=True, upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
