# Generated by Django 5.2.9 on 2026-02-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employeedocument_delete_employeefixeddocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
