# Generated by Django 5.2.9 on 2026-03-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_attendance_employee_and_more'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='entries',
            name='assigned_to_staff',
        ),
        migrations.RemoveField(
            model_name='entries',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='post',
            name='staff',
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='entries',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_assigned_to', to='managers.manager'),
        ),
        migrations.AddField(
            model_name='entries',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
