# Generated by Django 5.2.9 on 2026-08-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_entries_blocker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='timesheet_attachments/'),
        ),
    ]
