# Generated by Django 5.2.17 on 2026-09-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_entries_attachment'),
        ('managers', '0002_manager_biometric_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managers.manager'),
        ),
    ]
