# Generated by Django 5.2.9 on 2026-09-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_attendance_options_employee_avatar_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='education_certificate',
            field=models.FileField(blank=True, null=True, upload_to='Files', verbose_name='Education Certificate'),
        ),
        migrations.AlterField(
            model_name='post',
            name='experience_letter',
            field=models.FileField(blank=True, null=True, upload_to='Files', verbose_name='Experience Letter'),
        ),
        migrations.AlterField(
            model_name='post',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='Files', verbose_name='Offer Letter'),
        ),
        migrations.AlterField(
            model_name='post',
            name='skill_certificate',
            field=models.FileField(blank=True, null=True, upload_to='Files', verbose_name='Skill Certificate'),
        ),
    ]
