# Generated by Django 5.2.9 on 2026-09-30 10:39

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_entries_approved_at_entries_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_address',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_birth_date',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_emergency_primary_phone1',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_emergency_primary_phone2',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_phone',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_pin_code',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_salary',
            field=core.encryption.EncryptedCharField(blank=True, default='350000', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_tel',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
